// Creates the devnet demo: three wallets (tenant, landlord, mediator), a test
// USDC mint, and some SOL + test USDC for the tenant. Writes app/.env.local.
//
//   node scripts/setup-demo.mjs   (run from app/) [path/to/funder-keypair.json]
//
// The funder pays for everything (default: ~/.config/solana/id.json).
// Re-running keeps existing wallets and the mint, and tops them up.
import { createMint, getOrCreateAssociatedTokenAccount, mintTo } from '@solana/spl-token'
import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from '@solana/web3.js'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
// ENV_FILE lets the public GitHub Pages build use its own wallets (e.g. .env.pages.local).
const envPath = join(root, process.env.ENV_FILE || '.env.local')
const rpc = process.env.RPC_URL || 'https://api.devnet.solana.com'
const connection = new Connection(rpc, 'confirmed')

const funderPath = process.argv[2] || join(homedir(), '.config', 'solana', 'id.json')
const funder = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(funderPath, 'utf8'))))

const env = Object.fromEntries(
  existsSync(envPath)
    ? readFileSync(envPath, 'utf8')
        .split('\n')
        .filter((l) => l.includes('='))
        .map((l) => [l.slice(0, l.indexOf('=')), l.slice(l.indexOf('=') + 1).trim()])
    : [],
)
const load = (key) => (env[key] ? Keypair.fromSecretKey(Uint8Array.from(JSON.parse(env[key]))) : Keypair.generate())
const tenant = load('VITE_TENANT_SECRET')
const landlord = load('VITE_LANDLORD_SECRET')
const mediator = load('VITE_MEDIATOR_SECRET')

console.log('Funder:', funder.publicKey.toBase58(), (await connection.getBalance(funder.publicKey)) / LAMPORTS_PER_SOL, 'SOL')

// Each demo wallet needs a little SOL for fees and account rent.
const topUp = { tenant: 0.3, landlord: 0.1, mediator: 0.1 }
const tx = new Transaction()
for (const [name, kp] of [['tenant', tenant], ['landlord', landlord], ['mediator', mediator]]) {
  const have = (await connection.getBalance(kp.publicKey)) / LAMPORTS_PER_SOL
  const need = topUp[name] - have
  if (need > 0.01) {
    tx.add(SystemProgram.transfer({ fromPubkey: funder.publicKey, toPubkey: kp.publicKey, lamports: Math.round(need * LAMPORTS_PER_SOL) }))
  }
}
if (tx.instructions.length) await sendAndConfirmTransaction(connection, tx, [funder])

let mint = env.VITE_MINT ? new PublicKey(env.VITE_MINT) : null
if (!mint || !(await connection.getAccountInfo(mint))) {
  mint = await createMint(connection, funder, funder.publicKey, null, 6)
  console.log('Created test USDC mint', mint.toBase58())
}

const tenantAta = await getOrCreateAssociatedTokenAccount(connection, funder, mint, tenant.publicKey)
await getOrCreateAssociatedTokenAccount(connection, funder, mint, landlord.publicKey)
await mintTo(connection, funder, mint, tenantAta.address, funder, 10_000 * 10 ** 6)

const secret = (kp) => JSON.stringify(Array.from(kp.secretKey))
writeFileSync(
  envPath,
  [
    '# Devnet demo wallets. Generated by scripts/setup-demo.mjs. Never put real funds here.',
    `VITE_RPC_URL=${rpc}`,
    `VITE_MINT=${mint.toBase58()}`,
    `VITE_TENANT_SECRET=${secret(tenant)}`,
    `VITE_LANDLORD_SECRET=${secret(landlord)}`,
    `VITE_MEDIATOR_SECRET=${secret(mediator)}`,
    '',
  ].join('\n'),
)

console.log('Tenant  ', tenant.publicKey.toBase58(), '(+10,000 test USDC)')
console.log('Landlord', landlord.publicKey.toBase58())
console.log('Mediator', mediator.publicKey.toBase58())
console.log('Wrote', envPath)
